apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ihgz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dmby-tenant/rhtap-demo-app/hacbs-test-project-ihgz@sha256:7287ae59284d56fb84c2a3b06deb6ce673f483fec80501c3a4b91b2431d447cb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
