apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ihgz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ihgz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ihgz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ihgz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ihgz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dmby-tenant/rhtap-demo-app/hacbs-test-project-ihgz@sha256:2bda7fed55e96ebf789f7da487e107aefee04d4a38fdf403e318c8ce5b75ef6b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
